services:
  - type: web
    name: vsch-bot
    env: go
    plan: free

    # Побудова та запуск
    buildCommand: make build-cmd
    startCommand: ./bot

    # Автодеплой з GitHub (з гілки main)
    autoDeploy: true
    branch: main

    # Health check
    healthCheckPath: /ping
