services:
  - type: web
    name: vsch-bot
    env: go
    plan: free

    # Побудова та запуск
    buildCommand: make build-cmd
    startCommand: ./bot

    # Автодеплой з GitHub (з гілки main)
    autoDeploy: true
    branch: main

    previewsEnabled: true

    # Health check
    healthCheckPath: /health
    healthCheckIntervalSeconds: 30
    healthCheckTimeoutSeconds: 10
    healthCheckFailureThreshold: 3

    # Змінні середовища
    envVars:
      - key: WEB_SERVER_PORT
        value: 8080
      - key: TELEGRAM_TOKEN
        sync: false
      - key: TG_ADMIN_ID
        sync: false
